# Generated by Django 5.2.12 on 2026-04-08 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_announcement_livesession_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
